server:
  port: 8085
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/books/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway=DEBUG: